# Generated by Django 5.1.4 on 2024-12-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtributeCSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atribute_name', models.CharField(max_length=50)),
            ],
        ),
    ]
