# Generated by Django 5.1.4 on 2024-12-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeAPI', '0002_atributecss'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtributeHTML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atribute_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='ButtonType',
        ),
    ]
