# Generated by Django 5.1.4 on 2024-12-15 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeAPI', '0003_atributehtml_delete_buttontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_num', models.IntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
            ],
        ),
        migrations.RenameModel(
            old_name='AtributeHTML',
            new_name='AttributeButton',
        ),
        migrations.RenameModel(
            old_name='AtributeCSS',
            new_name='AttributeImage',
        ),
    ]
