# Generated by Django 5.1.4 on 2024-12-15 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeAPI', '0004_attributetitle_rename_atributehtml_attributebutton_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttributeButton',
        ),
        migrations.DeleteModel(
            name='AttributeImage',
        ),
        migrations.DeleteModel(
            name='AttributeTitle',
        ),
    ]
